### ISSUE TITLE
Defining = "type"

### ISSUE THREAD

**Issue by jimmyzhen** [clingen-data-model/data-exchange-shared-json#12]
> "type": "clinicalValidity"

https://github.com/clingen-data-model/data-exchange-shared-json/blob/87fa6290e08a78d16eb022a487a1c8254dd1603e/json-structure-phase1/Gene%20Curation%20Interface/gci.json#L10

Is this to indicate it is coming from the GCI?  We don't have a field like this at the moment, but you are already asking about the jsonMessageVersion, so would this be redundant?

**Comment by tnavatar** [comment]
There will be a topic in Kafka for gene curations, I'm going to process everything published to that topic as a gene curation, so 'type' in this instance is not strictly necessary.

Later on (phase 2), when we're modeling this with JSON-LD, almost everything gets tagged with a "@type" (https://json-ld.org if you're interested in wandering down that rabbit hole early).

**Comment by sgoehringer** [comment]
@jimmyzhen Tristan confirmed that the JSON will be submitted to a specific Kafka topic so it will be possible to track GCI data that way... but when the JSON leaves Kafka it would be helpful to tag is some how.  Granted, the iri would provide a hint and as you mentioned, we could provide a hint in the version.  Am I being too verbose by adding another element to the JSON?

**Comment by jimmyzhen** [comment]
@tnavatar @sgoehringer Thank you both for the clarification on this **type** property. So we can probably close this Github issue since the property in question is not meant to be mapped any data in the GCI application.
