### ISSUE TITLE
Defining = "pmid"

### ISSUE THREAD

**Issue by jimmyzhen** [clingen-data-model/data-exchange-shared-json#14]
```
"pmid": 
{
	"publications": [
		{
			"title": "[Oxygen affinity of haemoglobin (author",
			"author": "Robert M",
			"pubdate": "1975 Jan-Feb",
			"source": "Bull Physiopathol (Nancy)",
			"uid": "111"
		}
	],
	"notes": 
	{
		"note": "Proband with "
	}
}
```

https://github.com/clingen-data-model/data-exchange-shared-json/blob/87fa6290e08a78d16eb022a487a1c8254dd1603e/json-structure-phase1/Gene%20Curation%20Interface/gci.json#L57

@sgoehringer where is the pmid #? (e.g. PMID:21345568) (totally made up) and what is the "uid"?

**Comment by sgoehringer** [comment]
@jimmyzhen Sorry, the PMID is the uid... would you like that to be updated?  That isn't a problem and it would be clearer.

**Comment by jimmyzhen** [comment]
@sgoehringer I think that it will be clearer for **uid** to be renamed as **pmid**. But then its parent's parent is also named **pmid**. Is there another term more suitable?

**Comment by sgoehringer** [comment]
@jimmyzhen What do you think about 'evidence'?

**Comment by sgoehringer** [comment]
the PMID portion of this discussion was addressed.  https://github.com/clingen-data-model/data-exchange-shared-json/commit/58804c71ab83ff2d9dc14b9b6749bd493937e61e

**Comment by jimmyzhen** [comment]
Hi @sgoehringer,

**"evidence"** is a suitable term. Thanks.

**Comment by sgoehringer** [comment]
Address - 8cf6e4b5ba67c0893a970c11b5628a974078a27a
