### ISSUE TITLE
Defining = "CuratorModifyCalculation"

### ISSUE THREAD

**Issue by jimmyzhen** [clingen-data-model/data-exchange-shared-json#17]
```
"CuratorModifyCalculation": 
    {
        "YesNo": "YES"
    },
```

@sgoehringer,

Do we actually need the "Yes"/"No" value?

Shall we provide the modified classification value for this if the curator selects an option? If not, we can set a `null` value to it.

**Comment by sgoehringer** [comment]
That should be fine!

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
