### ISSUE TITLE
Defining = "ValidContradictoryEvidence"

### ISSUE THREAD

**Issue by jimmyzhen** [clingen-data-model/data-exchange-shared-json#18]
```
"ValidContradictoryEvidence": 
    {
        "YesNo": "YES",
```

@sgoehringer  Does this include proband and experimental evidence?  We calculate both on  the fly.  Or, is it only proband (genetic) contradictory evidence that gives this a yes value?

**Comment by sgoehringer** [comment]
@jimmyzhen That is a good question... we ask the curator to check this off via our simple interface... I'm not exactly sure why the curator would have checked this.  Do we need to loop in a curator?

**Comment by selinad** [comment]
@sgoehringer I just took a look at the SOP and it looks like any type of contradictory evidence can contribute; however, I'll check with the curator as ours is a calculated value and the curator makes this choice when entering into your calculator.

**Comment by selinad** [comment]
@sgoehringer from the curators, we can use calculated value from interfaces as to whether there is contradictory evidence.

@jimmyzhen we don't collect contradicts for case-control right now -- we may need to add that in (waiting on curator feedback and will make ticket if needed).

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
