### ISSUE TITLE
Defining = "Summary"

### ISSUE THREAD

**Issue by jimmyzhen** [clingen-data-model/data-exchange-shared-json#20]
```
"summary": 
{
	"ExperimentalEvidenceTotal": "1.5",
	"GeneticEvidenceTotal": "4",
	"EvidencePointsTotal": "5.5",
	"CalculatedClassification": "CONFLICTING EVIDENCE REPORTED",
	"CalculatedClassificationDateISO8601": "2017-01-25T00:00:00",
	"CuratorClassification": "STRONG",
	"CuratorClassificationDate ISO8601": "2017-01-25T00:00:00",
	"CuratorClassificationNotes": "CURATOR CLASSIFICATION NOTES",
	"FinalClassification": "DEFINITIVE",
	"FinalClassificationDateISO8601": "2017-01-25T00:00:00",
	"FinalClassificationNotes": "FINAL CLASSIFICATION NOTES"
}
```

@sgoehringer Can you clarify which are the **calculated classification** and **modified classification**? And what is **"CalculatedClassification": "CONFLICTING EVIDENCE REPORTED"**?

**Comment by wrightmw** [comment]
@sgoehringer 
Thanks for your clarification on the call today. As I understand it:
"CalculatedClassification" is the Classification calculated from the scoring matrix
"CuratorClassification" is the Classification as selected by the curator (please confirm that this represents the "provisional" classification selected by the curator as ready be reviewed?)
"FinalClassification" is the Classification approved by the reviewer

We currently only store 2 Classification fields:
"autoClassification" is equivalent to "CalculatedClassification"
"alteredClassification" shows the altered Classification if the curator has opted to modify the calculated Classification. An important note here is that if the curator does not modify the classification then this field will be null.

We will use the "classificationStatus" field to determine whether a Classification is "in progress, "provisional", or "approved".

Therefore your "CuratorClassification" is equivalent to "autoClassification" (or "alteredClassification" instead if that has been selected) when the Classification has a "classificationStatus" of "provisional".

We have not implemented the approval yet, however under our current schema your "FinalClassification" would be equivalent to "autoClassification" (or "alteredClassification" instead if that has been selected) when the Classification has a "classificationStatus" of "approved".

I was just discussing this with @jimmyzhen and we could potentially provide a field for the Classification that is marked "classificationStatus" as "provisional" and this could be named "provisionalClassification  (this would then be equivalent to your "CuratorClassification"), and a field for the Classification that is marked "classificationStatus" as "approved" and this could be named  "approvedClassification" (this would then be equivalent to your "FinalClassification")
...however, we will have to discuss this some more to see whether this is a good idea or not and to check for any ramifications.

**Comment by sgoehringer** [comment]
@wrightmw Thanks for the details... I am wrapping my head around this and had a few questions.  Also, for the case of this discussion lets use your fields (at least some of them) and lets assume we don't have any right or wrong answers... I just want to make sure I am following.

QuestionA: **autoClassification** - The value of this field is generated by the math/magic behind the scenes and is always expected. Is that what you are thinking?

QuestionB: **alteredClassification** - The value of this field would only be sent IF a person decides to alter the autoClassification above. Is that what you are thinking?

QuestionC: If a curation was sent with a 'provisional' status and an alteredClassification of 'Limited' it essentially means an curator (not expert) has reviewed this, disagreed with the autoClassification, and provisionally it is set as Limited.  Does that sound about right?

QuestionD: If a curation is sent with a 'approved' status with only a autoClassification of 'Definitive' it essentially means an expert has reviewed this, agreed autoClassification, and approved classification would be Definitive.  Does that sound about right?

P.S. - I understand you are reviewing with Jimmy the idea to generate additional approvedClassifications and based those discussions things could change.

**Comment by wrightmw** [comment]
@sgoehringer Sure, let's work through these so that we are all sure of each other's Summary definitions.

AnswerA: Yes, "autoClassification" is entirely automatically generated by our algorithm behind the scenes, and would always be expected in our output to you.

AnswerB: Yes, "alteredClassification" would only be expected in our output to you when a curator has decided to select an alternative Classification to the "autoClassification".

AnswerC: Yes.

AnswerD: Yes.

Answer. P.S: Yes, we are currently looking into our options.

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
