### ISSUE TITLE
Disease names in gene-disease pairs

### ISSUE THREAD

**Issue by ronakypatel** [clingen-data-model/data-exchange-shared-json#21]
In the AWG curated data, there is no place where name of diseases are captured for **each** OMIM. We **do** store OMIM identifiers but not the names associated with each of them. One can easily get the names from the identifiers, though.

Say for example: the gene-disease pairs given here (https://www.clinicalgenome.org/working-groups/actionability/projects-initiatives/actionability-evidence-based-summaries/) for **ARVD**  include:

Arrhythmogenic Right Ventricular Dysplasia,Familial, 9; ARVD9
Arrhythmogenic Right Ventricular Dysplasia, Familial, 8; ARVD8
Arrhythmogenic Right Ventricular Dysplasia,Familial, 11; ARVD11
Arrhythmogenic Right Ventricular Dysplasia, Familial, 5; ARVD5
Arrhythmogenic Right Ventricular Dysplasia, Familial, 10; ARVD10

In the AWG provided summaries (https://www.clinicalgenome.org/site/assets/files/6360/binning_arvd_05252016.pdf), there is no mention of any of these subtypes (although OMIMs are there) directly, neither it is in the curation interface.

In the curation interface, the following information is there:

Document: Arrhythmogenic Right Ventricular Dysplasia

Has genes: PKP2, DSP, DSC2, TMEM43, DSG2

With these pairs:
DSC2⇔610476
DSG2⇔610193 
DSP⇔607450
PKP2⇔609040
TMEM43⇔604400

Providing just OMIMs (and not actual name) should hopefully be fine?

**Comment by sgoehringer** [comment]
We don't need the Disease name and we can remove that... the OMIM will be fine.

**Comment by sgoehringer** [comment]
Since we are on this topic... I wanted to inquire about one more item.  Does the interface associate DSC2⇔610476 with a specific intervention?  The following would be the example

DSC2⇔610476
Example Outcome 1 / Example Intervention A = Score ABC

DSG2⇔610193
Example Outcome 2 / Example Intervention B = Score XYZ

Both of the above would be associated to a single report like the one you referenced earlier.

**Comment by ronakypatel** [comment]
No.

However, the gene might be. But in that case, the outcome will be named as 

Gene1 - Outcome1 / Intervention 1
Gene2 - Outcome1 / Intervention 1

**Comment by sgoehringer** [comment]
Okay, but if I understand things correctly... if this curation was done for "Gene1 & Gene2" and "OMIM1 & OMIM2" it isn't possible (or maybe it isn't necessary) to associate interventions with specific pairs?  I think this means the following would occur on a single curation.

Gene1 - "Outcome1 / Intervention 1" is connected to OMIM1 & OMIM2
Gene2 - "Outcome1 / Intervention 1" is connected to OMIM1 & OMIM2

The reason I am asking is what if "Gene2 - Outcome1 / Intervention 1" shouldn't be associated to OMIM2 and should only be related to OMIM1?  Maybe this isn't how things are curated though and may not be an issue.

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
