### ISSUE TITLE
Clarify Disease/Condition Ontologies

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/data-exchange-shared-json#23]
@ronakypatel Would it also be possible to list the disease/condition ontologies when you have a moment.  Sorry if I already asked this, I just want to be certain.

**Comment by ronakypatel** [comment]
OMIM For disease in most case. As I mentioned in one of our conversation there is at least on disease i know that AWG curated but does not have OMIM.

**Comment by sgoehringer** [comment]
@ronakypatel I recall that, yes... Regarding the one that doesn't have an OMIM ID...  It's not that the curation is connected to an 'unknown' condition, OMIM just doesn't have an appropriate ID at this time.  Is that correct?

**Comment by ronakypatel** [comment]
Thats true

**Comment by sgoehringer** [comment]
Out of curiosity... What do you allow them to do/choose in the interface now to move past this step?  Or maybe more to the point, what data do you expect to share, if any?

**Comment by ronakypatel** [comment]
That's a great question. Here the document title will describe the disease.

**Comment by sgoehringer** [comment]
@tnavatar Looping you in on this... how do you think we can handle when a OMIM ID isn't provided because an OMIM ID isn't yet available... thoughts?  I think we will need to explore this for the GCI as well because I've heard they offer a free form input.

**Comment by ronakypatel** [comment]
Exactly in the way you allow Ovarian Cancer -  RAD51C RAD51D BRIP1 here:

https://www.clinicalgenome.org/working-groups/actionability/projects-initiatives/actionability-evidence-based-summaries/

I think at this moment, for this entry, we have associated OMIM in interface so should be fine.

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
