### ISSUE TITLE
Affiliation ID structure

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/data-exchange-shared-json#25]
@wrightmw We probably need to start thinking about the naming/id convention for curation affiliations.  I don't think it should be as simple number like 1 or 2 or anything too random because it may be possible for the different curation tools auto generate something that is already used.

My sense is the affiliates would fall into the following general areas...
- Gene Curation
- Variant Curation (Do we need to differentiate between VCI and CIVIC applications?)
- Actionability
- Dosage
- CADRe

Based on the assumption above, it feels affiliations will be associated to a specific and single curation effort. If that is true, a Affiliation ID can't be shared by multiple curation groups... IE. a Gene Curation Committee and a Variant Expert Panel will need separate IDs. Don't you think think so?  So maybe something like... (Just throwing out ideas)  
- cdwgGene1                      = ABC Gene Curation Committee
- cdwgVariant1                   = ZYX Variant Curation Expert Panel
- awgActionability1             = Clinical Actionability 
- gcwgDosage1                   = Dosage Sensitivity 

Let me know if you think I out in left field and I am open to all ideas!

**Comment by wrightmw** [comment]
Hi @sgoehringer 

What you are describing here are more similar to affiliation aliases. We prefer IDs to be namespace agnostic, so we would recommend that the AffilationIDs are just numbers.
Using namespace as part of an ID can cause problems further down the line. For instance, within your schema there may be one curation group that submits curations to both the GCI and VCI.

@jimmyzhen Please feel free to add any comments about how this impacts on our schema.

**Comment by sgoehringer** [comment]
@wrightmw I totally understand... if we go with straight ID (like 1, 2, 3) then we need to make sure that all of the curation teams are on the same page so same ID isn't shared by multiple affiliations.  We could go with an IRI concept and get ahead of things since this most-likely will hang around for a long time.  Glad to are having the discussions and curious what @jimmyzhen and @tnavatar think.

**Comment by jimmyzhen** [comment]
@sgoehringer,

Can you give us an example of the ID with an IRI concept (that you may have in mind)? Thanks.

**Comment by sgoehringer** [comment]
Sure, it was earlier on the thread but email doesn't show that...  anyway. here you go...

cdwgGene1 = ABC Gene Curation Committee
cdwgVariant1 = ZYX Variant Curation Expert Panel
awgActionability1 = Clinical Actionability
gcwgDosage1 = Dosage Sensitivity

An IRI one... I haven't taken a lot of time to think about it but...
http://www.clinicalgenome.org/affiliation/1
or
http://www.clinicalgenome.org/affiliation/cdwgGene1

The benefit of the IRI is when other groups start up we can request (or software can check) the IRI is in use and/or matches what they were expecting.  Again, just brainstorming on the fly a little.

**Comment by jimmyzhen** [comment]
@sgoehringer,

Thank you for the clarification.

Would it be potentially problematic if we assign numeric-only IDs, something like 5-digit IDs ranging from 10000-99999?

I can't help but associate strings like "cdwgGene1" with aliases or symbols.

**Comment by wrightmw** [comment]
I agree with @jimmyzhen 
The AffiliationIDs only need to be unique. The simplest implementation would be to use numbers. We can hook other information, such as Group or Lab names, domain area, etc. to the AffiliationID.

**Comment by tnavatar** [comment]
Numeric is fine, so long as you prefix the numeric ID with your domain (just to make it clear who owns the identifier:

Here’s an example of an OK IRI:
https://www.ncbi.nlm.nih.gov/clinvar/submitters/505720/

**Comment by wrightmw** [comment]
@sgoehringer On the large GCI call today, Jenny Goldstein ( @jennygoldstein ) presented the plans for UNC to develop a curator tracking system.  Within this tracking system Affiliations would have to be specified so that the workflow of working groups could be tracked. Our team also needs AffiliationIDs in place for when we implement Group login for the interfaces, which will be soon because this feature is planned for the next release (the one after our release this week). Therefore, I think we need to think about generating the AffiliationID list sooner rather than later.  The coordinators have a list on confluence of all the working groups.
This list does not have be comprehensive right now, we just need to know the format.

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
