### ISSUE TITLE
Request for information regarding "EvidenceOfSegregationInOneOrMoreFamilies"

### ISSUE THREAD

**Issue by bryanwulf** [clingen-data-model/data-exchange-shared-json#27]
In the SOP5 data sample, under "EvidenceOfSegregationInOneOrMoreFamilies":
https://github.com/clingen-data-model/data-exchange-shared-json/blob/master/json-structure-phase1/Gene%20Curation%20Interface/gci-sop-v5.json#L154

it looks like "Evidence" may be separated by family (the numbered keys: "1", "2" and "3").  Is this necessary, or would it suffice to include all the evidence ("Publications"/article data) for all families contributing to the scores ("Value" and "Tally") under a single key (either "1" or "EvidenceOfSegregationInOneOrMoreFamilies")?

If the ultimate result of the message is to generate a summary view of the data, like the following:
https://search.clinicalgenome.org/kb/gene-validity/3221

my guess is that combining all the evidence would be acceptable.

**Comment by sgoehringer** [comment]
@bryanwulf the result that you shared (https://search.clinicalgenome.org/kb/gene-validity/3221) is is one that was formatted for SOP4.  When I was asked display SOP5 data the team asked to have the different family information to be broken out by family (Example - https://search.clinicalgenome.org/kb/gene-validity/9511)  Is this possible?

**Comment by bryanwulf** [comment]
@sgoehringer Yes, I believe it's possible and can be seen in the first sample message I published earlier today (#29).

One informational note:
As a result of the GCI's data structure/hierarchy (every family added as unique "child" evidence to articles), there will always be a 1:1 relationship between the numbered keys and "Publications" (1 article per numbered key).  The same family may be added to multiple articles (same data submitted via form), but the GCI doesn't recognize them as just one (each submission creates a new family).

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
