### ISSUE TITLE
Request for information regarding "uid"

### ISSUE THREAD

**Issue by bryanwulf** [clingen-data-model/data-exchange-shared-json#28]
In the SOP5 sample data, the value of "uid" (under "Publications") is a number:
https://github.com/clingen-data-model/data-exchange-shared-json/blob/master/json-structure-phase1/Gene%20Curation%20Interface/gci-sop-v5.json#L55

The GCI/VCI identify articles by their PMID.  When providing the "uid", should the number be prefixed with "PMID:"?  I think this would be meaningful data and might be useful if the message is to be displayed like the following (specifically, the article citations under "PMIDs/Notes"):
https://search.clinicalgenome.org/kb/gene-validity/3221

**Comment by sgoehringer** [comment]
@bryanwulf thank you for pointing that out and it is change UID to be PMID so you don't need to prefex anything.  I just updated the sample json with that change https://github.com/clingen-data-model/data-exchange-shared-json/commit/08596403f53be460dd8091f9bc1be0a14f5a7af2
Feel free to close this issue if this looks okay on your side.

**Comment by bryanwulf** [comment]
Sounds good, will close the issue... thanks!
