### ISSUE TITLE
Sample Message from GCI (#1)

### ISSUE THREAD

**Issue by bryanwulf** [clingen-data-model/data-exchange-shared-json#29]
I'm opening this issue as a place to analyze/discuss a sample classification published from the GCI.  A PDF of the corresponding evidence summary (from the GCI) can be found here:
[GCI_Evidence_Summary_for_Message_0.pdf](https://github.com/clingen-data-model/data-exchange-shared-json/files/1881722/GCI_Evidence_Summary_for_Message_0.pdf)

Message location:
topic: gene_validity_dev
partition: 0
offset: 0

A couple initial notes regarding the message:
1. Where the requirements/logic to determine a key's value hasn't been finalized, a "TO BE DETERMINED" value has been added (as a placeholder).  The affected keys are:

- "curationVersion" - if programmatically possible (still under consideration), the intention is to provide a value representing the number of times the classification has been published
- "iri" (under "conditions") - in the future, this will likely be a UUID (representing the disease), but the ability to input disease metadata as free text (vs. selecting a MONDO ID) may complicate things
- "Value" (both under "CaseControlData") - selecting a study type (between "Single variant analysis" and "Aggregate variant analysis") is optional in the GCI, so it may not be possible to distinguish where scores/evidence belong

2. The "statusPublishFlag" key has a value of "Unpublish" because the data used to set it (a boolean that will eventually be updated when a GCI user clicks a button to publish a classification) isn't available yet.

**Comment by bryanwulf** [comment]
@sgoehringer @tnavatar Just curious if you've had a chance to examine/process the sample messages on the gene_validity_dev topic?

**Comment by sgoehringer** [comment]
@bryanwulf thanks for following up!  @tnavatar and I are slated to review items early next week.  I'll keep you posted.

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
