### ISSUE TITLE
Defining = "statusFlag"

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/data-exchange-shared-json#3]
"statusFlag" Options
in-process - The curation is in the works
provisional - Fits all of the criteria but not yet expert approved
approved - Expert curated

The above status flags show where a curation is/was in the curation process. 

https://github.com/clingen-data-model/data-exchange-shared-json/blob/87fa6290e08a78d16eb022a487a1c8254dd1603e/json-structure-phase1/Gene%20Curation%20Interface/gci.json#L8

**Comment by jimmyzhen** [comment]
@sgoehringer,

The GCI has the equivalent field, but does not yet support the value of "Approved."

The other values for this status are "In progress" and "Provisional" in our schema.

**Comment by sgoehringer** [comment]
@jimmyzhen Great... do you expect the follow values being sent...

In process - The curation is in the works
Provisional - Fits all of the criteria but not yet expert approved
Approved - Expert curated

Are the definitions of the values reasonable with what you are thinking?  Also we are glad to change the value/label for 'approved' if you have a clearer concept.  I don't imagine additional ones at this time, do you?

**Comment by selinad** [comment]
Hi @sgoehringer -- the above are correct (reasonable with what we are thinking).  @wrightmw may have the best idea -- I believe "Approved" works.

I can't think of additional ones at the moment unless we have to worry about one that has been removed or deleted? (a Classification, not a Gene:disease record).

**Comment by wrightmw** [comment]
@sgoehringer FYI... sorry for only just seeing this:
> In process - The curation is in the works
Provisional - Fits all of the criteria but not yet expert approved
Approved - Expert curated

We have "In progress" not "In process"

**Comment by sgoehringer** [comment]
Oh, that is fine... same concept though, right?

**Comment by wrightmw** [comment]
@sgoehringer Yeah, same concept:
In progress - The curation is in the works
Provisional - Curation has signed off on it and it is ready for review
Approved - It's been expert reviewed and signed off (by whoever has responsibility to approve for that Affiliation)

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
