### ISSUE TITLE
Sample Message from GCI (#2)

### ISSUE THREAD

**Issue by bryanwulf** [clingen-data-model/data-exchange-shared-json#30]
I'm opening this issue as a place to analyze/discuss a sample classification published from the GCI.  A PDF of the corresponding evidence summary (from the GCI) can be found here:
[GCI_Evidence_Summary_for_Message_1.pdf](https://github.com/clingen-data-model/data-exchange-shared-json/files/1881936/GCI_Evidence_Summary_for_Message_1.pdf)

Message location:
topic: gene_validity_dev
partition: 0
offset: 1

A couple initial notes regarding the message:
1. The "CuratorClassification" key has a value of "No Modification" (and "CuratorModifyCalculation" has "YES") to signify that the GCI user selected the "No Modification" option when creating the classification.  I imagine this behavior should be changed, such that selecting the aforementioned option would prevent the "CuratorClassification" key from being included in the message (and "CuratorModifyCalculation" would have "NO")?

2. The "Value" key is absent under "RescueInNonHumanModelOrganism".  I'll be looking into this, but my initial guess is that it's a result of the score being set to zero.

3. The "Publications" key is present under "SegregationEvidence", but the GCI's evidence summary has an empty section for family segregation data.  Assuming this mismatch is a problem, I'll need to investigate the logic that determines which articles belong in the message's segregation evidence (and possibly update that logic to check for the existence of probands within the family).

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
