### ISSUE TITLE
Add new fields data model for segregation LOD score data in revised SOP

### ISSUE THREAD

**Issue by jimmyzhen** [clingen-data-model/data-exchange-shared-json#31]
Given the updated segregation LOD score data shown in the classification matrix, we will need to include the new key/value pairs in the Kafka messages streamed to Data Exchange.

**The new fields are for:**
1. Total count for candidate evidence
2. Total count for exome evidence
3. Sum of all candidate LOD scores
4. Sum of all exome LOD scores
5. Total sum of all LOD scores

**Comment by cbizon** [comment]
Here's how we do this in the data exchange model, perhaps you will find it useful:
http://dataexchange.clinicalgenome.org/interpretation/entities/FamilyCosegregationStatement.html
http://dataexchange.clinicalgenome.org/interpretation/entities/AggregateCosegregationStatement.html

**Comment by jimmyzhen** [comment]
Thanks for the pointers, @cbizon!

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
