### ISSUE TITLE
Please review first draft

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/data-exchange-shared-json#33]
@tnavatar can you review through this draft for JSON that would be basked into the KB site and the marketing site would use to seed information needed to display curation totals for our curation activities and affiliations. I did add a few actives in the JSON that won't be in our KB site but that's just to keep track and maybe set a format.

This is just to get the ideas going and glad to explain so you can better improve/evolve.  This is also intended to be private and only intended for use by the marketing site for the foreseeable future.

You can find the file here: 
https://github.com/clingen-data-model/data-exchange-shared-json/blob/0cdec8917fc81df203f6d4fd4b16530e99734527/json-curation-tally/clingen-curation-tally-json-v1

**Comment by tnavatar** [comment]
That structure seems doable—I think my major concerns are about how things are going to be grouped based on the new affiliation group structure. When were you looking to implement this?

**Comment by sgoehringer** [comment]
@tnavatar I hope in the next 45 days or so... possible?  Even if all of the data is not in place but to return the affilationID with the # of curations.  I guess the tricky part will be only the number of 'active' ones and not just the total.  I'm not as concerned about the totals for this first pass.  I'm curious on how the current curations in the site though get assigned to the new affiliates... it may be that the GCI needs to resend to the DX or the groups need to go back in and touch them all again.

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.

**Comment by sgoehringer** [comment]
https://github.com/clingen-data-model/data-exchange-shared-json/issues/35
https://github.com/clingen-data-model/data-exchange-shared-json/issues/34
