### ISSUE TITLE
Defining = "CurationGroup":

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/data-exchange-shared-json#6]
"CurationGroup": 
        {
            "Id": "GCWGid1",
            "Name": "Cardiovascular - Aortopathy"
        },

We need to define an appropriate ID schema for the curation group to use.  This would be used by the GCI and the website to be able to appropriately match work.  The website may not need the name but might as well share it so it is easier to confirm matches and structure.

**Comment by jimmyzhen** [comment]
The ClinGen GCI currently does not have **CurationGroup** defined, but we have talked about a light implementation of groups in which the curators belong.

**Comment by sgoehringer** [comment]
Great point!  Matt seemed like he was thinking about this... should I circle up with him and work options?

**Comment by jimmyzhen** [comment]
Sounds good.

**Comment by sgoehringer** [comment]
Matt, I just assigned this to us as a reminder to follow up about possible ideas/solution on how to handle groups.

**Comment by wrightmw** [comment]
@sgoehringer Hey Scott, sure... more than happy to liaise on this.

**Comment by sgoehringer** [comment]
@wrightmw I am bring in some notes from an email exchange on Sept 28...

> I want to ask you about the nomenclature you use for IDs for Groups. We would prefer that these are named as Affiliation IDs instead of Group IDs.
> We already use 'Group' for something different in our database. Also, in our interfaces we will need IDs not just for ClinGen working groups but also for other organizations (such as private labs). 
> Therefore we would prefer to use the term Affiliation ID,  which would enable us to label all of the affiliations that a curator might have.

I agree with this alteration.

**Comment by sgoehringer** [comment]
Addressed - 2da23a2d93e3638cf5f240c3ac29c99be1b36aaf and d15ad13bb58150bc3fe1be2889eb126ac46c965b
