### ISSUE TITLE
Defining = "jsonMessageVersion":

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/data-exchange-shared-json#7]
"jsonMessageVersion": "GCI.1",

I am open to ideas on the best way to handle the message versioning.  The goal is simply be able to know how to process the JSON structure if it changes for some reason.

**Comment by selinad** [comment]
@sgoehringer did we discuss using date/timestamps at some point, or is this in addition?

**Comment by sgoehringer** [comment]
This would be for curationVersion.  I created an issue here https://github.com/clingen-data-model/data-exchange-shared-json/issues/8
