### ISSUE TITLE
Defining = "conditions":

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/data-exchange-shared-json#9]
"conditions": 
        [
            {
                "ontology": "OMIM",
                "curie": "OMIM:114480",
                "name": "BREAST CANCER ",
                "uri": "OMIM114480",
                "iri": "http://purl.obolibrary.org/obo/OMIM_114480"
            }
        ],

Jimmy, when you have a chance can you list the different ontologies that you expect to be sharing just so we are on the same page.

**Comment by selinad** [comment]
@sgoehringer -- for disease, the following terminologies are possible:

1. Orphanet
2. DO
3. OMIM
4. NCIt
5. free text term associated with one or both of following: HPO term(s), free text description

Note: 1-4 must be IDs that exist in MonDO (and, apologies, 5 is not a terminology ;-))

**Comment by jimmyzhen** [comment]
What @selinad said.

Is the **conditions** array meant to represent all diseases associated with all the evidence in the approved classification?

FYI, the **iri** object property is not currently defined in GCI, and so we need to update the schema and patch all the production disease records.

**Comment by sgoehringer** [comment]
Yes, the conditions array may be many... so (and by the way, the following simply my adding fake Orphanet data)

"conditions":
[
{
"ontology": "OMIM",
"curie": "OMIM:114480",
"name": "BREAST CANCER ",
"uri": "OMIM114480",
"iri": "http://purl.obolibrary.org/obo/OMIM_114480"
},
{
"ontology": "Orphanet",
"curie": "Orpha:114480",
"name": "Orphanet's BREAST CANCER name",
"uri": "ORPHA114480",
"iri": "http://purl.obolibrary.org/obo/ORPHA114480"
}
],

@jimmyzhen - What do you have now as the identifier?  OMIM:114480 or OMIM114480 ?

**Comment by jimmyzhen** [comment]
@sgoehringer,

The identifier format we have now is **OMIM_114480** since I tried to avoid encoding special characters in the URIs and queries. Then I simply replaced the underscore instances with semicolons in the UI.

**Comment by sgoehringer** [comment]
Thanks!  I will check into some things.

**Comment by tnavatar** [comment]
@selinad @jimmyzhen @sgoehringer 

The IRI is the primary identifier for ontology terms on the website, if it's possible to incorporate it in the message it would be helpful and practical down the road, as the message becomes more linked-data friendly.

For the free-text case, would it be possible or reasonable for you to construct your own IRI for the label? (For example: 
{
"iri": "https://curation.clinicalgenome.org/terms/12345", // Using whatever internal identifier you might have for the label
"name": "disease without a home"
}

My thinking is that this would make the import work a little more cleanly in our system, and also provide a point of reference should the term receive an identifier in a real ontology that could be updated down the line.

HPO terms described by free-text could be a little messy. Do you have plans to support HPO natively at any point? We haven't had a use case yet for making HPO discoverable on the website, but it's on the near-term horizon, as structural variants are usually labelled with HPO terms.

**Comment by sgoehringer** [comment]
Cleanup - Closing old issue.
